apiVersion : apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world-app
    tier: backend
spec:
  progressDeadlineSeconds: 3600
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
      tier: backend
  template: 
    metadata:
      labels:
        app: hello-world-app
        tier: backend
        intility-logging: default
    spec:
      containers:
        - name: hello-world-app
          image: dingipacr.azurecr.io/hello-world:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8080
